xhprof_gui_list:
    pattern:  /profilings
    defaults: { _controller: XhprofGuiBundle:Profiling:list }
xhprof_gui_show:
    pattern:  /profilings/{id}/{sort_by_metrics}/{sort_direction}
    defaults: { _controller: XhprofGuiBundle:Profiling:show, sort_by_metrics: null, sort_direction: null }
xhprof_gui_test:
    pattern: /profiling/test
    defaults: { _controller: XhprofGuiBundle:Profiling:test }
